### ISSUE TITLE
Obsoleted by kernel fix

### ISSUE THREAD

**Issue by bdrung** [AdamGleave/elgato-camlink-workaround#3]
As your README.md explains, there is a bug in the firmware which breaks all pixel formats except the first one. I developed a quirk to fix the buggy firmware and submitted it to the upstream Linux: https://lore.kernel.org/lkml/20210325213458.51309-1-bdrung@posteo.de/

So once this patch is accepted, backported to older kernel released, and tribbled into the disto kernels this workaround script is not needed any more.

**Comment by AdamGleave** [comment]
Sweet, thanks for doing this! That is a much cleaner solution :) Let me know when it's accepted and I'll update the README to make it clear what kernel versions this script is not needed for.

**Comment by bdrung** [comment]
I'll do.

BTW, even with that firmware bug fixed, Firefox on Ubuntu does not support any of the pixel formats: https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1906454

The workaround until Firefox supports it: Use Chromium. That works fine with the firmware fix.

**Comment by bdrung** [comment]
Since I have three computers that need this kernel patch, I started maintaining this patched linux kernel in my PPA for Ubuntu 20.10 (groovy): https://launchpad.net/~bdrung/+archive/ubuntu/ppa

I plan to maintain this linux kernel in the PPA until the patch is included in the latest Ubuntu release.

**Comment by LeoniePhiline** [comment]
@bdrung Thanks for your efforts! I hope these fixes get merged into the kernel as well as firefox soon. (Before the pandemic is over. :D) 

Did you have a chance to report to upstream firefox? See https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1906454/comments/5

**Comment by ghost** [comment]
Is it in 5.12?

**Comment by bdrung** [comment]
Sadly not. I sent the patch four times, but got no response yet. You can follow the progress on https://lore.kernel.org/lkml/?q=Fix+pixel+format+change+for+Elgato+Cam+Link+4K

**Comment by bdrung** [comment]
Good news: The fix is now merged upstream and will be part of v5.14:
* fix commit: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4c6e0976295add7f0ed94d276c04a3d6f1ea8f83
* merge: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=31e798fd6f0ff0acdc49c1a358b581730936a09a

The fix is also currently included in Ubuntu: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1932367

**Comment by LeoniePhiline** [comment]
Fantastic! Thank you for your efforts!

**Comment by AdamGleave** [comment]
Nice, well done!

**Comment by bdrung** [comment]
So, the fix was backported to the stable releases. The fix is included in:
* 4.4.276
* 4.9.276
* 4.14.240
* 4.19.198
* 5.4.134
* 5.10.52
* 5.12.19
* 5.13.4
* 5.14-rc1

**Comment by LeoniePhiline** [comment]
Wow, big impact. Much better than expected!

**Comment by mcnaveen** [comment]
So, I can start using Camlink without any additional configuration? Like Plug and Play?

**Comment by rektide** [comment]
My camera (Z-Cam E1) was on photo mode. Switching it to video mode gave me 1920x1080x59.940fps! :tada:

~~With apologies, I'm only getting 640x480. I do get a couple different formats, at least. Ha.~~

```sh
$ v4l2-ctl -d /dev/video0 --list-formats-ext
ioctl: VIDIOC_ENUM_FMT
	Type: Video Capture

	[0]: 'YUYV' (YUYV 4:2:2)
		Size: Discrete 640x480
			Interval: Discrete 0.017s (59.940 fps)
	[1]: 'NV12' (Y/UV 4:2:0)
		Size: Discrete 640x480
			Interval: Discrete 0.017s (59.940 fps)
	[2]: 'YU12' (Planar YUV 4:2:0)
		Size: Discrete 640x480
			Interval: Discrete 0.017s (59.940 fps)

$ uname -a
Linux rocinante.example.com 6.18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.18~rc7-1~exp1 (2025-11-24) x86_64 GNU/Linux
```

~~Really quite the bummer. Personally, can not recommend the Cam Link 4K at this time.~~
